import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const banner = `/* Knowledge Map - generated by esbuild. See the source repository for TypeScript files. */`;
const production = process.argv[2] === 'production';
const projectRoot = dirname(fileURLToPath(import.meta.url));

const context = await esbuild.context({
	absWorkingDir: projectRoot,
	banner: { js: banner },
	entryPoints: [join(projectRoot, 'src', 'main.ts')],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	loader: { '.jpg': 'dataurl' },
	target: 'es2021',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: join(projectRoot, 'main.js'),
	minify: production,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
